name: Business-Support-System CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build common data module
      run: mvn -B clean install --file ./data/pom.xml
    - name: Build hrs module
      run: mvn -B clean package --file ./hrs/pom.xml
    - name: Build brt module
      run: mvn -B clean package --file ./brt/pom.xml
    - name: Build cdr module
      run: mvn -B clean package --file ./cdr/pom.xml
    - name: Build crm module
      run: mvn -B clean package --file ./crm/pom.xml
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: v0.7.0
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push hrs
      uses: docker/build-push-action@v4
      with:
        context: ./hrs
        push: true
        tags: ibadullayevali/hrs
    - name: Build and push brt
      uses: docker/build-push-action@v4
      with:
        context: ./brt
        push: true
        tags: ibadullayevali/brt
    - name: Build and push cdr
      uses: docker/build-push-action@v4
      with:
        context: ./cdr
        push: true
        tags: ibadullayevali/cdr
    - name: Build and push crm
      uses: docker/build-push-action@v4
      with:
        context: ./crm
        push: true
        tags: ibadullayevali/crm
