name: Business-Support-System CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build common data module
      run: |
        cd ./data
        mvn clean install
        cd ..
    - name: Build hrs module
      run: |
        cd ./hrs
        mvn clean package
        cd ..
    - name: Build brt module
      run: |
        cd ./brt
        mvn clean package
        cd ..
    - name: Build cdr module
      run: |
        cd ./cdr
        mvn clean package
        cd ..
    - name: Build crm module
      run: |
        cd ./crm
        mvn clean package
        cd ..
